import turtle
s = turtle.getscreen()
t = turtle.Turtle()
turtle.bgcolor ("lightblue")
t.pen(pencolor= "black", fillcolor= "yellow", pensize=5, speed=9)
t.begin_fill()
t.circle(150)
t.end_fill()
t.penup()
t.lt(90)
t.fd(100)
t.pendown()
t.fd(50)
t.rt(90)
t.penup()
